#!/usr/bin/env node
'use strict';

/**
 * Stage 3 bootstrap diagnostic (cross-platform).
 * Collects M1/M2 status, optional gen2/gen3 artifacts, handler slice diffs.
 *
 * Usage:
 *   node scripts/diagnose-stage3.js
 *   node scripts/diagnose-stage3.js --gen2 /path/to/gen2.elf --gen3 /path/to/gen3.elf
 *   node scripts/diagnose-stage3.js --run-bootstrap   # requires WSL/Linux
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync, spawnSync } = require('child_process');

const root = path.join(__dirname, '..');
const yoyoTy = path.join(root, 'projects/yoyo.ty');
const DATA_MAP_OFF = 0x9000 + 0xfe00;
const CODE_END_OFF = DATA_MAP_OFF + 0x400;

function sha256File(p) {
  if (!fs.existsSync(p)) return null;
  return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
}

function fileSize(p) {
  return fs.existsSync(p) ? fs.statSync(p).size : null;
}

function readCodeEnd(elfPath) {
  if (!fs.existsSync(elfPath)) return null;
  const b = fs.readFileSync(elfPath);
  if (b.length < CODE_END_OFF + 4) return null;
  return b.readUInt32LE(CODE_END_OFF);
}

function cmpBytes(aPath, bPath, maxPairs = 20) {
  if (!fs.existsSync(aPath) || !fs.existsSync(bPath)) return { ok: false, reason: 'missing file' };
  const a = fs.readFileSync(aPath);
  const b = fs.readFileSync(bPath);
  const pairs = [];
  const len = Math.max(a.length, b.length);
  for (let i = 0; i < len && pairs.length < maxPairs; i++) {
    const av = i < a.length ? a[i] : null;
    const bv = i < b.length ? b[i] : null;
    if (av !== bv) pairs.push({ offset: i, a: av, b: bv });
  }
  let total = 0;
  for (let i = 0; i < len; i++) {
    const av = i < a.length ? a[i] : null;
    const bv = i < b.length ? b[i] : null;
    if (av !== bv) total++;
  }
  return { ok: total === 0, total, sizeA: a.length, sizeB: b.length, pairs };
}

function runNode(script, args = []) {
  const r = spawnSync(process.execPath, [path.join(root, 'scripts', script), ...args], {
    cwd: root,
    encoding: 'utf8',
    timeout: 120000,
  });
  return { code: r.status, stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim() };
}

function hasWsl() {
  try {
    const r = spawnSync('wsl', ['-e', 'true'], { encoding: 'utf8', timeout: 15000 });
    return r.status === 0;
  } catch {
    return false;
  }
}

function runBootstrapNative() {
  const wslRoot = root.replace(/\\/g, '/').replace(/^([A-Za-z]):/, (_, d) => `/mnt/${d.toLowerCase()}`);
  const cmd = `cd '${wslRoot}' && bash scripts/bootstrap-native.sh 3`;
  try {
    const out = execSync(`wsl bash -lc ${JSON.stringify(cmd)}`, {
      encoding: 'utf8',
      timeout: 300000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { ok: true, output: out };
  } catch (e) {
    return { ok: false, output: (e.stdout || '') + (e.stderr || ''), code: e.status };
  }
}

function parseArgs(argv) {
  const opts = { gen2: null, gen3: null, gen1: path.join(root, 'build/yoyo'), runBootstrap: false, out: null };
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === '--gen2' && argv[i + 1]) opts.gen2 = argv[++i];
    else if (argv[i] === '--gen3' && argv[i + 1]) opts.gen3 = argv[++i];
    else if (argv[i] === '--gen1' && argv[i + 1]) opts.gen1 = argv[++i];
    else if (argv[i] === '--out' && argv[i + 1]) opts.out = argv[++i];
    else if (argv[i] === '--run-bootstrap') opts.runBootstrap = true;
  }
  return opts;
}

function handlerSliceReport(gen2Path) {
  const r = runNode('compare-handler-slices.js', gen2Path ? ['--gen2', gen2Path] : []);
  return { code: r.code, text: [r.stdout, r.stderr].filter(Boolean).join('\n') };
}

function main() {
  const opts = parseArgs(process.argv);
  const date = new Date().toISOString().slice(0, 10);
  const reportPath = opts.out || path.join(root, 'docs', `stage3-diagnose-${date}.md`);
  const lines = [];

  const section = (title) => {
    lines.push('');
    lines.push(`## ${title}`);
    lines.push('');
  };

  lines.push(`# Stage 3 diagnostic (${date})`);
  lines.push('');
  lines.push('Auto-generated by `scripts/diagnose-stage3.js`.');

  section('Environment');
  lines.push(`- platform: ${process.platform}`);
  lines.push(`- node: ${process.version}`);
  lines.push(`- wsl available: ${hasWsl()}`);

  section('M1 — tir-check');
  const m1 = runNode('tir-check.js', [yoyoTy]);
  lines.push('```');
  lines.push(m1.stdout || m1.stderr || '(no output)');
  lines.push('```');
  lines.push(`- exit: ${m1.code}`);

  section('M2 — compare-backends');
  const m2 = runNode('compare-backends.js');
  lines.push('```');
  lines.push(m2.stdout || m2.stderr || '(no output)');
  lines.push('```');
  lines.push(`- exit: ${m2.code}`);

  if (opts.runBootstrap) {
    section('M3 — bootstrap-native.sh 3');
    if (!hasWsl()) {
      lines.push('**SKIP:** WSL/Linux not available on this host.');
    } else {
      const bs = runBootstrapNative();
      lines.push('```');
      lines.push(bs.output.trim() || '(empty)');
      lines.push('```');
      lines.push(`- result: ${bs.ok ? 'PASS' : 'FAIL'}`);
    }
  }

  section('Artifacts');
  const artifacts = [
    ['gen1 (build/yoyo)', opts.gen1],
    ['gen2', opts.gen2],
    ['gen3', opts.gen3],
  ];
  for (const [label, p] of artifacts) {
    if (!p) {
      lines.push(`- ${label}: (not provided)`);
      continue;
    }
    lines.push(`- ${label}: \`${p}\``);
    lines.push(`  - size: ${fileSize(p) ?? 'missing'}`);
    lines.push(`  - sha256: ${sha256File(p) ?? 'missing'}`);
    const ce = readCodeEnd(p);
    if (ce !== null) lines.push(`  - codeEnd (data+0xFE400): ${ce} (0x${ce.toString(16)})`);
  }

  if (opts.gen2 && opts.gen3) {
    section('gen2 vs gen3 byte diff');
    const diff = cmpBytes(opts.gen2, opts.gen3);
    lines.push(`- identical: ${diff.ok}`);
    lines.push(`- differing byte pairs: ${diff.total}`);
    lines.push(`- sizes: ${diff.sizeA} vs ${diff.sizeB}`);
    if (diff.pairs.length) {
      lines.push('');
      lines.push('| offset | gen2 | gen3 |');
      lines.push('|--------|------|------|');
      for (const p of diff.pairs) {
        lines.push(`| 0x${p.offset.toString(16)} | ${p.a === null ? '—' : '0x' + p.a.toString(16)} | ${p.b === null ? '—' : '0x' + p.b.toString(16)} |`);
      }
    }
  }

  section('Handler slices (Node compile vs gen2 scan-emitted)');
  if (!opts.gen2) {
    lines.push('Provide `--gen2 /path/to/gen2.elf` (from bootstrap) for handler comparison.');
  } else {
    const hs = handlerSliceReport(opts.gen2);
    lines.push('```');
    lines.push(hs.text || '(no output)');
    lines.push('```');
    lines.push(`- exit: ${hs.code}`);
  }

  section('Known blockers (from docs/PENDING.md)');
  lines.push('- gen2 scan-emitted handlers ≠ Node `compileLinux` handlers (H_00/H_01 LoadFile init)');
  lines.push('- gen2 self-host often yields `codeEnd=30` (scan loop never emits handlers)');
  lines.push('- Resolution: TIR single codegen path (`docs/evolution.md`), not per-handler meta-emitter parity');

  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, lines.join('\n') + '\n');

  console.log('Wrote', reportPath);
  console.log('');
  console.log(lines.join('\n'));

  const fail = m1.code !== 0 || m2.code !== 0;
  process.exit(fail ? 1 : 0);
}

main();
